Parameters:
  BucketName:
    Description: The SPA storage bucket
    Type: String
  ConfigurationPath:
    Default: .config
    Description: The path to access all the configuration values
    Type: String
  IndexFileName:
    Default: index.html
    Description: The name of the file that represents the index
    Type: String
  VariablePrefix:
    Description: The variable namespace prefix
    Type: String
  VersionKey:
    Description: The version key that the spa lives under
    Type: String
Resources:
  ConfigurationFunction:
    Properties:
      CodeUri: s3://spa-lambda-storage/98ced520fd3a4d86b34b5cfd1a6ff9c1
      Environment:
        BUCKET_NAME:
          Ref: BucketName
        INDEX_FILE_NAME:
          Ref: IndexFileName
        VARIABLE_PREFIX:
          Ref: VariablePrefix
        VERSION_KEY:
          Ref: VersionKey
      Events:
        ApiRoot:
          Properties:
            Method: get
            Path:
              Fn::Sub: /${ConfigurationPath}
          Type: Api
      Handler: handler.serveConfiguration
      Runtime: nodejs6.10
    Type: AWS::Serverless::Function
  FileOrIndexFunction:
    Properties:
      CodeUri: s3://spa-lambda-storage/98ced520fd3a4d86b34b5cfd1a6ff9c1
      Environment:
        BUCKET_NAME:
          Ref: BucketName
        INDEX_FILE_NAME:
          Ref: IndexFileName
        VARIABLE_PREFIX:
          Ref: VariablePrefix
        VERSION_KEY:
          Ref: VersionKey
      Events:
        ApiRoot:
          Properties:
            Method: get
            Path: /{any+}
          Type: Api
      Handler: handler.serveFileOrIndex
      Runtime: nodejs6.10
    Type: AWS::Serverless::Function
  IndexFunction:
    Properties:
      CodeUri: s3://spa-lambda-storage/98ced520fd3a4d86b34b5cfd1a6ff9c1
      Environment:
        BUCKET_NAME:
          Ref: BucketName
        INDEX_FILE_NAME:
          Ref: IndexFileName
        VARIABLE_PREFIX:
          Ref: VariablePrefix
        VERSION_KEY:
          Ref: VersionKey
      Events:
        ApiRoot:
          Properties:
            Method: get
            Path: /
          Type: Api
      Handler: handler.serveIndex
      Runtime: nodejs6.10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
